# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      wget https://raw.githubusercontent.com/bumgardnera07/azure-functions-templates/dev/Functions.Templates/Templates/HttpTrigger-JavaScript/function.json
      wget https://raw.githubusercontent.com/bumgardnera07/azure-functions-templates/dev/Functions.Templates/Templates/HttpTrigger-JavaScript/index.js
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

- task: AzureResourceManagerTemplateDeployment@3
  name: CreateFunctionApp
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureFunction-conn'
    subscriptionId: '2eb04934-401d-4233-82c4-6c80ab35d49c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ResourceGroupGABFunctionDeploy'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/bumgardnera07/FunctionPipelineRepo/main/CreateFunction/azuredeploy.json'
    overrideParameters:
    deploymentMode: 'Complete'
    deploymentName: 'DeployPipelineTemplate'
    deploymentOutputs: 'ARMDeploymentOutputs'
- task: AzureCLI@2
  retryCountOnTaskFailure: 10
  inputs:
    azureSubscription: 'AzureFunction-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az functionapp deployment source config-zip --src $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip  -g ResourceGroupGABFunctionDeploy -n $(ArmDeploymentOutputs.functionAppName.value)'
