# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  name: CreateFunctionApp
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureFunction-conn'
    subscriptionId: '2eb04934-401d-4233-82c4-6c80ab35d49c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ResourceGroupGABFunctionDeploy'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/bumgardnera07/FunctionPipelineRepo/main/CreateFunction/azuredeploy.json'
    overrideParameters:
    deploymentMode: 'Complete'
    deploymentName: 'DeployPipelineTemplate'
    deploymentOutputs: 'ARMDeploymentOutputs'
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'gebumgar (2eb04934-401d-4233-82c4-6c80ab35d49c)'
    appType: 'functionApp'
    appName: '$(CreateFunctionApp.ArmDeploymentOutputs.functionAppName.value)'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureFunction-conn'
    subscriptionId: '2eb04934-401d-4233-82c4-6c80ab35d49c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ResourceGroupGABFunctionDeploy'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/bumgardnera07/FunctionPipelineRepo/main/CreateFunction/DeleteTemplate.json'
    deploymentMode: 'Complete'
    deploymentName: 'DeleteResources'