# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest
steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                wget https://raw.githubusercontent.com/bumgardnera07/azure-functions-templates/dev/Functions.Templates/Templates/HttpTrigger-JavaScript/function.json
                wget https://raw.githubusercontent.com/bumgardnera07/azure-functions-templates/dev/Functions.Templates/Templates/HttpTrigger-JavaScript/index.js
          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
              archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

          - task: AzureResourceManagerTemplateDeployment@3
            name: CreateFunctionApp
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'gebumgar (2eb04934-401d-4233-82c4-6c80ab35d49c)'
              subscriptionId: '2eb04934-401d-4233-82c4-6c80ab35d49c'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'ResourceGroupGABFunctionDeploy$(Build.BuildId)'
              location: 'East US'
              templateLocation: 'URL of the file'
              csmFileLink: 'https://raw.githubusercontent.com/bumgardnera07/FunctionPipelineRepo/main/CreateFunction/azuredeploy.json'
              overrideParameters: '-appName GABFUNCAPP$(Build.BuildId) '
              deploymentMode: 'Complete'
              deploymentName: 'DeployPipelineTemplate'
              deploymentOutputs: 'ARMDeploymentOutputs'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                echo $(ArmDeploymentOutputs.functionAppName.value)
          - task: AzureCLI@2
            retryCountOnTaskFailure: 10
            inputs:
              azureSubscription: 'gebumgar (2eb04934-401d-4233-82c4-6c80ab35d49c)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az functionapp deployment source config-zip --src $(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip  -g ResourceGroupGABFunctionDeploy$(Build.BuildId) -n $(ArmDeploymentOutputs.functionAppName.value)'

          - task: AzureFunctionApp@1
            retryCountOnTaskFailure: 10
            continueOnError: true
            inputs:
              azureSubscription: 'gebumgar (2eb04934-401d-4233-82c4-6c80ab35d49c)'
              appType: 'functionApp'
              appName: $(ArmDeploymentOutputs.functionAppName.value)
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
              deploymentMethod: 'auto'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                sleep 1800
          - task: AzureFunctionApp@1
            retryCountOnTaskFailure: 10
            continueOnError: true
            inputs:
              azureSubscription: 'gebumgar (2eb04934-401d-4233-82c4-6c80ab35d49c)'
              appType: 'functionApp'
              appName: $(ArmDeploymentOutputs.functionAppName.value)
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
              deploymentMethod: 'auto'
            
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: 'gebumgar (2eb04934-401d-4233-82c4-6c80ab35d49c)'
                subscriptionId: '2eb04934-401d-4233-82c4-6c80ab35d49c'
                action: 'DeleteRG'
                resourceGroupName: 'ResourceGroupGABFunctionDeploy$(Build.BuildId)'
              
  